name: Python Package using Conda

on: 
 schedule:
    - cron: "55 8 *  * 1/4"    #heduled at 08:01 (UTC+8) everyday #每天早上八点零一分打卡
 workflow_dispatch:

 
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run the program
        
      run: |
          python -m pip install --upgrade pip
          pip install Beautifulsoup4 
          pip install -r requirements.txt
          python3 ./main.py
